### ISSUE TITLE
No error message for the user when the fields are empty during login

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/learn-it#2]
<img width="1269" alt="screen shot 2015-10-27 at 6 06 25 am" src="https://cloud.githubusercontent.com/assets/2946769/10750066/50689fb4-7c71-11e5-9f82-e57a635f1419.png">

**Comment by unicodeveloper** [comment]
Why is the form to the right hand side? Why is it not at the center. Please fix ASAP!

**Comment by kola-er** [comment]
Resolved
