### ISSUE TITLE
No error message for the user when the fields are empty during registration

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/learn-it#3]
<img width="1267" alt="screen shot 2015-10-27 at 6 10 56 am" src="https://cloud.githubusercontent.com/assets/2946769/10750088/875f7a24-7c71-11e5-90b6-6024a37bd2ca.png">

**Comment by unicodeveloper** [comment]
Why is the form to the right hand side? Why is it not at the center. Please fix ASAP!

**Comment by kola-er** [comment]
Resolved
