### ISSUE TITLE
Facebook authentication doesn't work, Remove your app from sandbox mode

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/learn-it#4]
Change the facebook app from sandbox to live, so that the facebook auth can work.

<img width="1260" alt="screen shot 2015-10-27 at 6 13 41 am" src="https://cloud.githubusercontent.com/assets/2946769/10750120/e9173edc-7c71-11e5-8bfa-8b8e2f104142.png">

**Comment by kola-er** [comment]
Resolved
