### ISSUE TITLE
If there is no video in a category, it should have a message that shows the user that there are no videos in that category yet

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/learn-it#5]
It shouldnt just be blank

<img width="1277" alt="screen shot 2015-10-27 at 6 15 44 am" src="https://cloud.githubusercontent.com/assets/2946769/10750144/44be4ca8-7c72-11e5-813a-f1ca2bca7d52.png">

**Comment by kola-er** [comment]
Resolved
