### ISSUE TITLE
Anytime I try to play a video, it just shows this error and the video doesnt play

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/learn-it#6]
Is it the kind of links that I paste or is there any particular type of youtube link users should be pasting

<img width="904" alt="screen shot 2015-10-27 at 6 17 36 am" src="https://cloud.githubusercontent.com/assets/2946769/10750185/9dc05774-7c72-11e5-8a9b-06336f0804ad.png">

Please Fix ASAP!

**Comment by kola-er** [comment]
Yes. The site supports only two youtube URL formats: `https://www.youtube.com/watch?v=DGa6MAibjzA` and `https://www.youtube.com/embed/DGa6MAibjzA`
