### ISSUE TITLE
Updating of avatar leads to error page

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/learn-it#9]
<img width="1280" alt="screen shot 2015-10-27 at 10 40 39 pm" src="https://cloud.githubusercontent.com/assets/2946769/10773483/d2edbb56-7cfb-11e5-92e9-08e6f1f5efa7.png">

<img width="1266" alt="screen shot 2015-10-27 at 10 40 30 pm" src="https://cloud.githubusercontent.com/assets/2946769/10773488/dd0ddb48-7cfb-11e5-8511-dc181994af5d.png">

When I click on update for the avatar without selecting nay avatar, it redirects me to an error page. Please fix!

**Comment by kola-er** [comment]
Stable now
